server:
  port: 8889

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-doc:
    path: /api-doc
  show-actuator: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    email: mailtestservice.122@gmail.com
    password: nisdeiphottbqdlj
    protocol: smtp
    isSSL: false
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: sendEmailGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"