jwt:
  signerkey: "dDrAdtWaqgCiilX7V4z7uxZ6rU7vlbaTgj02FUswCkegR6H1TANcd5LipojaqhKN"
  valid-duration: 3600
  refreshable-duration: 36000

server:
  port: 8888
  servlet:
    context-path: /identity

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-doc:
    path: /api-doc
  show-actuator: true

spring:
  application:
    name: identity-service

  datasource:
    url: "jdbc:mysql://localhost:3306/manager_service"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  elasticsearch:
    rest:
      uris: "http://localhost:9200"

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

