server:
  port: 8880

spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8888
          predicates:
            - Path=/identity/**